replicaCount: 1

image:
  repository: maven-hello-world
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

resources: {}
