{{- if eq .Values.workload.type "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maven-hello-world.fullname" . }}
  labels:
    {{- include "maven-hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workload.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "maven-hello-world.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "maven-hello-world.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "maven-hello-world.podSpec" . | nindent 6 }}
{{- else if eq .Values.workload.type "Job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "maven-hello-world.fullname" . }}
  labels:
    {{- include "maven-hello-world.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.workload.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.workload.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "maven-hello-world.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "maven-hello-world.podSpec" . | nindent 6 }}
{{- else }}
{{- fail "workload.type must be either Deployment or Job" }}
{{- end }}
