name: CI/CD Pipeline

on:
  push:
    branches:
      - devops-assignment
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and package application
    uses: ./.github/workflows/java-build.yml
